package appconfig

// RabbitMQURL ...
const RabbitMQURL = "159.65.220.217:5672"

// RabbitMQUsername ...
const RabbitMQUsername = "admin"

// RabbitMQPassword ...
const RabbitMQPassword = "Password123"

// RabbitMQRpcQueue ...
const RabbitMQRpcQueue = "rpc-die-queue"

// PublicAPIAddress ...
const PublicAPIAddress = ":9000"

// PublicAPIFullAddress ...
const PublicAPIFullAddress = "127.0.0.1:9000"

// PublicAPIUrl ...
const PublicAPIUrl = "http://localhost"

// PublicAPIWriteTimeout ...
const PublicAPIWriteTimeout = 15

// PublicAPIReadTimeout ...
const PublicAPIReadTimeout = 15

// PublicAPICountriesPattern ...
const PublicAPICountriesPattern = "/countries"

// PublicAPITeamsPattern ...
const PublicAPITeamsPattern = "/teams"

// DieAPIAddress ...
const DieAPIAddress = ":8000"

// DieAPIUrl ...
const DieAPIUrl = "http://localhost"

// DieAPICountriesPattern ...
const DieAPICountriesPattern = "/api/mysql/countries"

// DieAPITeamsPattern ...
const DieAPITeamsPattern = "/api/mysql/teams"
